{% set name = "odc-dscache" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/odc-dscache-{{ version }}.tar.gz
  sha256: b36f62d9c0c4371cf9c1526bb772a617bda85d338ca85cf4b0be057839db575a

build:
  entry_points:
    - slurpy = odc.dscache.apps.slurpy:cli
    - dstiler = odc.dscache.apps.dstiler:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - datacube
    - pandas
    - psycopg2
    - zstandard
    - python-lmdb
    - click
    - toolz

test:
  imports:
    - odc
  commands:
    - pip check
    - slurpy --help
    - dstiler --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/opendatacube/odc-dscache/
  summary: ODC Dataset File Cache
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Ariana-B
