{% set name = "odc-dscache" %}
{% set version = "1.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6264f9479e3b777d24596bcbfdf0f5720491dc13749bd665027e6e131dba7ef3

build:
  entry_points:
    - slurpy = odc.dscache.apps.slurpy:cli
    - dstiler = odc.dscache.apps.dstiler:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - datacube >=1.9.0
    - pandas
    - psycopg2
    - zstandard
    - python-lmdb
    - click
    - toolz

test:
  imports:
    - odc
  commands:
    - pip check
    - slurpy --help
    - dstiler --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/opendatacube/odc-dscache/
  summary: ODC Dataset File Cache
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Ariana-B
